// Übungsbibliothek mit ausführlichen Beschreibungen
// Format: Setup → Bewegung → wichtigste Fehler/Hinweise
// e: true = wird üblicherweise einseitig (unilateral) trainiert
//
// Namens-Regel: Namen sind die EINZIGE Quelle der Wahrheit für Tracking.
// Trainingspläne und Plan-Imports verwenden ausschließlich diese Namen,
// damit Progressionen pro Übung sauber zusammenlaufen.

export const EXERCISE_LIB = {
  "Maschine": [
    { n: "Beinpresse", e: true, d: "Setup: Füße schulterbreit mittig auf Platte, Knie ca. 90° in der Ausgangsposition, unterer Rücken am Polster. Bewegung: Gewicht weg drücken bis Knie fast gestreckt (nicht durchstrecken!), kontrolliert zurück bis Knie 90°. Fehler: Knie nach innen kippen, Steiß vom Polster lösen, durchstrecken." },
    { n: "Beinbeuger", e: true, d: "Setup: Bäuchlings, Polster knapp über Achillessehne, Knie über Drehachse. Bewegung: Fersen kontrolliert zum Gesäß ziehen, kurz halten, langsam zurück. Fehler: Hüfte vom Polster heben, Schwung holen, nicht voll ausstrecken am Ende." },
    { n: "Beinstrecker", e: true, d: "Setup: Sitzend, Polster knapp über Sprunggelenk, Knie über Drehachse, Rücken angelehnt. Bewegung: Beine strecken bis fast voll, oben kurz halten, langsam zurück. Fehler: Schwung, Becken kippt nach vorn, abruptes Absenken." },
    { n: "Adduktoren", e: false, d: "Setup: Sitzend, Polster innen an den Knien, Beine im Komfortbereich gespreizt. Bewegung: Beine kontrolliert zusammendrücken, kurz halten, sehr langsam öffnen. Fehler: Zu weite Spreizung (Leiste!), zu schnelles Öffnen, Hohlkreuz." },
    { n: "Abduktoren", e: false, d: "Setup: Sitzend, Polster außen an den Knien, Knie hüftbreit. Bewegung: Knie nach außen drücken bis Endspannung, kurz halten, kontrolliert zurück. Fehler: Oberkörper kippt mit, Schwung, Atem anhalten." },
    { n: "Brustpresse", e: true, d: "Setup: Sitz so, dass Griffe auf mittlerer Brusthöhe sind, Schulterblätter zusammen und unten, Füße fest. Bewegung: Griffe kontrolliert nach vorn drücken bis fast gestreckt, langsam zurück bis leichte Dehnung. Fehler: Ellbogen ganz durchstrecken, Schultern nach vorn rollen, Pause oben statt unten." },
    { n: "Schulterpresse", e: true, d: "Setup: Sitzend, Griffe auf Ohrhöhe, Rücken am Polster, Core fest. Bewegung: Über Kopf drücken bis fast gestreckt, kontrolliert zurück bis Ellbogen knapp unter 90°. Fehler: Hohlkreuz, Schultern hochziehen, ruckartig." },
    { n: "Latzug", e: true, d: "Setup: Oberschenkel unter Polster, Stange im weiten Obergriff, Schultern aktiv nach unten gezogen. Bewegung: Stange Richtung obere Brust ziehen, Ellbogen Richtung Hüfte, Schulterblätter zusammen. Kontrolliert nach oben. Fehler: Mit dem Oberkörper schwingen, Stange in den Nacken ziehen, Schultern hochziehen." },
    { n: "Latzug enger Griff", e: false, d: "Setup: Wie Latzug, aber V-Griff oder schulterbreiter Untergriff. Bewegung: Griff zur Brust ziehen, Ellbogen eng am Körper. Stärker für Bizeps und unteren Lat. Fehler: Schwingen, zu weit nach unten ziehen." },
    { n: "Rudermaschine (brustgestützt)", e: true, d: "Setup: Brust an Polster, Griffe locker, Schulterblätter entspannt. Bewegung: Griffe Richtung Hüfte ziehen, Schulterblätter aktiv zusammenführen, Ellbogen am Körper, kurz halten. Kontrolliert zurück. Fehler: Mit dem Rücken vom Polster lösen, nur die Arme arbeiten lassen, ruckartig." },
    { n: "Rudermaschine (sitzend)", e: false, d: "Setup: Sitz mit aufrechtem Rücken, Brust raus, Knie leicht gebeugt, Griffe gefasst. Bewegung: Schulterblätter zuerst zusammen, dann Ellbogen entlang Hüfte ziehen. Kontrolliert zurück, Arme strecken, ohne den Rücken zu runden. Fehler: Mit dem Oberkörper schwingen, Rücken runden in der Endposition." },
    { n: "Bizepscurls", e: false, d: "Setup: Sitzend an Bizepsmaschine, Oberarme komplett auf Polster, Hände im Untergriff, Schultern hinten. Bewegung: Unterarme heben bis volle Beugung, kurz halten, langsam absenken bis fast gestreckt. Fehler: Ellbogen vom Polster lösen, Schwung, oben mit den Schultern nach vorn rollen." },
    { n: "Trizepsmaschine", e: false, d: "Setup: Sitzend mit Polster über den Oberarmen, Hände an Griffen. Bewegung: Unterarme nach vorn/unten strecken, voll ausstrecken, langsam zurück. Fehler: Mit dem Oberkörper drücken, Ellbogen flattern, abruptes Absenken." },
    { n: "Rückenstrecker", e: false, d: "Setup: Hüfte am Polster, Füße fixiert, Oberkörper nach vorn abgesenkt. Bewegung: Kontrolliert aufrichten bis gerade Linie (nicht überstrecken!), kurz halten, langsam absenken. Fehler: Überstrecken (Hohlkreuz), Schwung holen, zu schweres Gewicht auf der Brust." },
    { n: "Butterfly", e: false, d: "Setup: Sitzend, Unterarme auf Polster, Ellbogen ca. 90°, Schultern hinten/unten. Bewegung: Polster vor der Brust zusammenführen, kurz halten, langsam öffnen bis zur leichten Brustdehnung. Fehler: Schultern nach vorn rollen, zu weit öffnen (Schmerz vorne), Schwung." },
    { n: "Reverse Butterfly", e: false, d: "Setup: Brust an Polster, Arme leicht gebeugt nach vorn, Schultern locker. Bewegung: Arme nach hinten/außen öffnen, Schulterblätter zusammen, kurz halten, kontrolliert zurück. Fehler: Mit dem Bizeps ziehen, Ellbogen durchstrecken, Schultern hochziehen." },
    { n: "Wadenheben Maschine", e: false, d: "Setup: Schultern unter Polster (oder Füße auf Platte je nach Maschine), Vorderfuß auf Kante, Fersen frei. Bewegung: Auf die Zehenspitzen drücken, kurz halten, langsam absenken bis Ferse unter Fußballen. Fehler: Schnellkraft statt Spannung, Knie beugen mit." },
    { n: "Hyperextension 45°", e: false, d: "Setup: Hüftknochen knapp über vorderem Polster, Füße fest, Arme verschränkt. Bewegung: Oberkörper kontrolliert nach unten klappen, dann bis gerade Linie aufrichten. Fehler: Überstrecken, Beschleunigung beim Aufrichten, Wirbelsäule rundlassen." },
  ],

  "Kabelzug": [
    { n: "Face Pulls", e: false, d: "Setup: Seilgriff auf Gesichtshöhe, gestaffelter Stand (ein Bein vorn) gegen Vorlehnen. Bewegung: Seil zur Stirn ziehen, Ellbogen hoch und außen, Schulterblätter zusammen, kurz halten. Fehler: Mit dem Körper kippen (deshalb Staffelstand!), Ellbogen fallen lassen, zu schwer." },
    { n: "Pallof Press", e: true, d: "Setup: Kabelzug auf Brusthöhe seitlich, Hände am Griff vor der Brust, Stand stabil seitlich zum Zug, Core fest. Bewegung: Arme langsam vor dem Körper ausstrecken (Anti-Rotation!), kurz halten, kontrolliert zurück. Fehler: Hüfte/Schultern drehen mit, Atem anhalten, Schwung." },
    { n: "Trizeps-Pushdown", e: false, d: "Setup: Stange/Seil auf hohe Position, Oberarme am Körper fixiert, leicht vorgebeugt. Bewegung: Nur die Unterarme strecken, Ellbogen bleiben am Körper, voll strecken, kurz halten, kontrolliert zurück. Fehler: Mit dem Oberkörper drücken, Ellbogen wandern nach vorn." },
    { n: "Schulter-Außenrotation", e: true, d: "Setup: Kabel auf Ellbogen-Höhe, Ellbogen 90° fest am Körper, Unterarm zeigt nach innen. Bewegung: Unterarm nach außen drehen, Ellbogen bleibt am Körper, kurz halten, kontrolliert zurück. Sehr leichtes Gewicht! Fehler: Ellbogen vom Körper lösen, Bewegung aus der Schulter statt Rotation." },
    { n: "Schulter-Innenrotation", e: true, d: "Setup: Kabel auf Ellbogen-Höhe, Ellbogen 90° am Körper, Unterarm nach außen. Bewegung: Unterarm nach innen vor den Körper drehen, kurz halten, kontrolliert zurück. Sehr leichtes Gewicht. Fehler: Mit dem Oberkörper drehen, Ellbogen wandert." },
    { n: "Cable Woodchop von oben", e: true, d: "Setup: Kabel hoch eingestellt, seitlicher Stand, Arme gestreckt am hohen Griff. Bewegung: Diagonal nach unten/außen ziehen, dabei aus der Hüfte rotieren, Arme bleiben gestreckt. Kontrolliert zurück. Fehler: Nur die Arme arbeiten lassen, kein Coreeinsatz." },
    { n: "Cable Woodchop von unten", e: true, d: "Setup: Kabel niedrig, seitlicher Stand, Arme gestreckt am unteren Griff. Bewegung: Diagonal nach oben/außen ziehen mit Hüftrotation, Arme gestreckt. Fehler: Mit dem Rücken statt aus der Hüfte arbeiten." },
    { n: "Cable Crunch", e: false, d: "Setup: Kniend vor dem Kabelzug, Seil hinter dem Kopf, Hüfte fix. Bewegung: Oberkörper aktiv einrollen (nicht nur die Hüfte beugen!), Bauch zusammenkneifen, kurz halten, kontrolliert zurück. Fehler: Aus der Hüfte ziehen, Arme als Hebel benutzen." },
    { n: "Cable Pull-Through", e: false, d: "Setup: Kabel niedrig, Stand mit Rücken zum Zug, Seil zwischen den Beinen, Knie leicht gebeugt. Bewegung: Mit der Hüfte nach hinten ziehen (Hip-Hinge), dann Hüfte explosiv nach vorn strecken, Gesäß anspannen. Fehler: Aus den Knien drücken, Rundrücken, mit den Armen ziehen." },
    { n: "Cable Row sitzend", e: false, d: "Setup: Sitzend am Bodenkabelzug, Beine leicht gebeugt, Brust raus, Griff gefasst. Bewegung: Schulterblätter zusammen, Griff zur unteren Brust/oberen Bauch ziehen, Ellbogen am Körper, kurz halten. Fehler: Mit dem Oberkörper schwingen, Rücken runden in der Streckung." },
    { n: "Lat Pull-Around", e: true, d: "Setup: Hohes Kabel, einarmig, seitlich vor der Maschine. Bewegung: Mit gestrecktem Arm nach unten/seitwärts ziehen bis zur Hüfte, leichte Lat-Kontraktion. Fehler: Mit Bizeps ziehen, Schulter hochziehen." },
  ],

  "Eigengewicht": [
    { n: "Plank", e: false, d: "Setup: Unterarmstütz, Ellbogen unter Schultern, Füße hüftbreit. Bewegung: Körper bildet eine Linie von Kopf bis Fersen, Bauch nach innen ziehen, Gesäß anspannen, normal atmen. Halten. Fehler: Hüfte zu hoch (wie Berg), zu tief (Hohlkreuz), Schultern hochziehen." },
    { n: "Seitstütz", e: true, d: "Setup: Seitlicher Unterarmstütz, Ellbogen unter Schulter, Beine gestapelt, Hüfte angehoben. Bewegung: Hüfte hoch halten, gerade Linie Kopf–Hüfte–Fuß, oberer Arm an Hüfte oder gestreckt nach oben. Fehler: Hüfte sackt ab, Schulter rollt nach vorn." },
    { n: "Side Plank Hip Lifts", e: true, d: "Setup: Seitstütz-Position. Bewegung: Hüfte langsam absenken (knapp über Boden), wieder hochdrücken über die seitliche Bauchmuskulatur. Fehler: Schwung, Hüfte zu weit absenken (Boden berühren)." },
    { n: "Liegestütze", e: false, d: "Setup: Hände schulterbreit unter den Schultern, Körper gestreckt wie Plank, Bauch fest. Bewegung: Brust kontrolliert Richtung Boden, Ellbogen ca. 45° zum Körper. Wieder hoch drücken, ohne Hüfte abzusenken. Fehler: Hüfte hängt durch, Ellbogen zu weit auseinander, Kopf nach unten." },
    { n: "Diamond Push-Ups", e: false, d: "Setup: Wie Liegestütz, aber Hände eng zusammen, Daumen+Zeigefinger bilden ein Dreieck. Bewegung: Brust zum Dreieck absenken, Ellbogen eng am Körper. Stärker für Trizeps. Fehler: Hüfte sinkt ab, Ellbogen weichen aus." },
    { n: "Decline Push-Ups", e: false, d: "Setup: Liegestütz mit Füßen erhöht (Bank, Treppenstufe). Bewegung: Wie normaler Liegestütz, betont stärker die obere Brust und Schultern. Fehler: Wie Liegestütz, plus: Hüfte abkippen lassen." },
    { n: "Pike Push-Ups", e: false, d: "Setup: Liegestütz-Position, dann Hüfte hoch (V-Form), Hände schulterbreit. Bewegung: Kopf Richtung Boden absenken (Schulterdruck-Bewegung), wieder hochdrücken. Fehler: Wenig Tiefe, Beine zu weit weg von den Händen." },
    { n: "Inverted Rows", e: false, d: "Setup: Stange (Smith oder TRX) hüfthoch, unter die Stange, Hände schulterbreit, Körper gestreckt, Fersen am Boden. Bewegung: Brust zur Stange ziehen, Schulterblätter zusammen, kurz halten, kontrolliert ablassen. Fehler: Hüfte sackt ab, Ellbogen zu weit raus." },
    { n: "Klimmzüge", e: false, d: "Setup: Stange im Obergriff schulterbreit, Schultern aktiv nach unten gezogen, leichte Hohlkörperspannung. Bewegung: Brust zur Stange ziehen (Kinn über Stange), Ellbogen Richtung Hüfte, kontrolliert ablassen bis fast gestreckt. Fehler: Schwung, hochzuckern statt ziehen, Schultern hochziehen." },
    { n: "Klimmzüge Untergriff", e: false, d: "Setup: Untergriff schulterbreit (Chin-Up). Bewegung: Wie Klimmzug, mehr Bizeps-Anteil, oft leichter. Fehler: Wie Klimmzug." },
    { n: "Bodyweight Squat", e: false, d: "Setup: Füße schulterbreit, leichte Außenrotation, Arme nach vorn als Gegengewicht. Bewegung: Hüfte zurück und nach unten, Knie folgen den Füßen, Tiefe bis Oberschenkel parallel oder tiefer. Aufrecht aufrichten. Fehler: Knie kippen nach innen, Fersen heben ab, Rücken rundet." },
    { n: "Bulgarian Split Squat", e: true, d: "Setup: Hinterer Fuß auf Bank (Spann unten), vorderer Fuß ca. 60–80 cm vor der Bank, Oberkörper aufrecht. Bewegung: Hinteres Knie kontrolliert Richtung Boden absenken, vorderes Knie über dem Sprunggelenk, hochdrücken über Ferse. Fehler: Vorderer Fuß zu nah (Knie überstreckt nach vorn), Oberkörper nach vorn fallen." },
    { n: "Reverse Lunge", e: true, d: "Setup: Aufrechter Stand, Hände an der Hüfte oder vor der Brust. Bewegung: Mit einem Bein einen großen Schritt nach hinten, hinteres Knie tief absenken, vorderes Knie über Sprunggelenk. Mit Vorderfuß-Power zurück in den Stand. Fehler: Vorderes Knie kippt nach innen, Oberkörper fällt vor." },
    { n: "Walking Lunges", e: true, d: "Setup: Aufrechter Stand. Bewegung: Großer Schritt nach vorn, hinteres Knie absenken bis fast Boden, mit der Vorderferse hochdrücken und direkt das andere Bein nach vorn. Wechselseitig laufen. Fehler: Zu kurzer Schritt, Oberkörper schwankt seitlich." },
    { n: "Step-Ups", e: true, d: "Setup: Stabile Bank/Box ca. Knie- bis Oberschenkelhöhe. Bewegung: Mit einem Fuß komplett auf die Box stellen, Fuß flach, durchstrecken, das hintere Bein anziehen ohne Schwung. Kontrolliert wieder absteigen. Fehler: Mit dem hinteren Fuß abstoßen (Schwung), Knie kippt." },
    { n: "Pistol Squat", e: true, d: "Setup: Auf einem Bein, anderes Bein gestreckt nach vorn, Arme als Gegengewicht. Bewegung: Hüfte zurück, langsam abkniebeugen bis Gesäß fast Boden, kontrolliert hoch. Sehr fortgeschritten — Anfänger an TRX/Türrahmen festhalten. Fehler: Knie kippt, Ferse hebt." },
    { n: "Glute Bridge", e: false, d: "Setup: Rückenlage, Knie aufgestellt schulterbreit, Fersen hüftnah, Arme entspannt. Bewegung: Hüfte nach oben drücken bis gerade Linie Knie–Hüfte–Schulter, oben Gesäß fest anspannen, kontrolliert ablassen. Fehler: Hohlkreuz oben, mit den Beinen drücken statt mit dem Po, Hüfte zu hoch." },
    { n: "Single-Leg Glute Bridge", e: true, d: "Setup: Wie Glute Bridge, ein Bein gestreckt in der Luft. Bewegung: Hüfte einbeinig hoch drücken, oben halten, kontrolliert ablassen. Stärkere Aktivierung pro Seite. Fehler: Hüfte kippt seitlich, Standbein arbeitet zu wenig." },
    { n: "Hip Thrust", e: false, d: "Setup: Schultern auf einer Bank, Füße flach hüftbreit, Knie 90° in Endposition, Arme entspannt. Bewegung: Hüfte aktiv nach oben drücken bis gerade Linie Knie–Hüfte–Schulter, Gesäß fest, kurz halten. Fehler: Hohlkreuz oben, Hüfte zu hoch." },
    { n: "Single-Leg Romanian Deadlift", e: true, d: "Setup: Auf einem Bein stehen, leicht gebeugt, anderes Bein leicht angehoben, Hüfte neutral. Bewegung: Aus der Hüfte (Hip-Hinge) nach vorn beugen, freies Bein hebt sich nach hinten als Waage, Rücken gerade. Aufrichten über das Standbein/Po. Fehler: Standbein durchstrecken, Rücken runden, Hüfte nicht parallel halten." },
    { n: "Dead Bug", e: true, d: "Setup: Rückenlage, Arme senkrecht nach oben, Knie 90° (Tisch-Position), unterer Rücken am Boden. Bewegung: Kontralaterales Paar (z.B. rechter Arm + linkes Bein) langsam Richtung Boden strecken, ohne dass der Rücken sich vom Boden abhebt. Zurück und Seite wechseln. Fehler: Hohlkreuz, Atem anhalten, zu schnell." },
    { n: "Bird Dog", e: true, d: "Setup: Vierfüßler, Hände unter Schultern, Knie unter Hüfte, neutraler Rücken. Bewegung: Kontralateral Arm und Bein gleichzeitig ausstrecken, kurz halten, kontrolliert zurück. Fehler: Hüfte rotiert mit, Hohlkreuz, Bewegung mit Schwung." },
    { n: "Superman", e: false, d: "Setup: Bauchlage, Arme nach vorn ausgestreckt, Beine gestreckt. Bewegung: Arme und Beine gleichzeitig vom Boden heben, kurz halten, kontrolliert ablassen. Fehler: Überstrecken, Kopf weit nach hinten, Schwung." },
    { n: "Crunches", e: false, d: "Setup: Rückenlage, Knie gebeugt, Hände an den Schläfen oder über der Brust gekreuzt. Bewegung: Oberkörper aktiv aus der Rumpfmuskulatur einrollen (Schulterblätter heben sich), kurz halten, kontrolliert zurück. Fehler: Mit den Armen den Kopf ziehen, Hüfte beugen statt einrollen, Schwung." },
    { n: "Reverse Crunch", e: false, d: "Setup: Rückenlage, Hände unter dem Gesäß oder an den Seiten, Beine 90°. Bewegung: Hüfte aktiv vom Boden anheben (Beine gehen Richtung Brust), kurz halten, langsam ablassen. Fehler: Schwung, Hüfte fällt zurück." },
    { n: "Hollow Hold", e: false, d: "Setup: Rückenlage, Arme über Kopf, Beine gestreckt. Bewegung: Arme, Schultern und Beine leicht vom Boden anheben, unterer Rücken bleibt fest am Boden, Bauch fest. Halten. Fehler: Unterer Rücken hebt vom Boden, zu hohe Hebung, Atem anhalten." },
    { n: "V-Ups", e: false, d: "Setup: Rückenlage, Arme über Kopf, Beine gestreckt. Bewegung: Arme und Beine gleichzeitig nach oben in V-Form, Hände Richtung Füße, kontrolliert zurück. Fehler: Schwung, unsauberes Einrollen." },
    { n: "Hanging Knee Raises", e: false, d: "Setup: An Klimmzugstange hängen, Schultern aktiv unten, Core fest. Bewegung: Knie gemeinsam Richtung Brust ziehen (Beckenkippung!), kurz halten, kontrolliert ablassen. Fehler: Schwung, nur die Beine heben ohne Becken-Kippung." },
    { n: "Hanging Leg Raises", e: false, d: "Setup: Wie Hanging Knee Raises, aber Beine gestreckt. Bewegung: Gestreckte Beine bis 90° (oder höher) heben, langsam ablassen. Fortgeschritten. Fehler: Schwung, Hohlkreuz beim Ablassen." },
    { n: "Mountain Climbers", e: false, d: "Setup: Hohe Liegestütz-Position, Bauch fest, Hüfte stabil. Bewegung: Knie abwechselnd schnell zur Brust ziehen, Hüfte bleibt hoch. Tempo nach Trainingsziel. Fehler: Hüfte wandert, Schultern verlassen Position." },
    { n: "Burpees", e: false, d: "Setup: Aufrechter Stand. Bewegung: Hocke → Hände auf Boden → Sprung in Liegestütz → Brust auf Boden → wieder hoch in Hocke → Strecksprung mit Klatschen. Fehler: Hüfte hängt im Liegestütz, kein voller Sprung, Brust berührt nicht Boden." },
    { n: "Burpees Broad Jump", e: false, d: "Setup: Wie Burpees. Bewegung: Statt Strecksprung ein Weitsprung nach vorn, dann sofort nächster Burpee. Cardio-intensiv. Fehler: Wie Burpees." },
    { n: "Bear Crawl", e: false, d: "Setup: Auf allen Vieren, Knie 2–3 cm über dem Boden, Rücken gerade. Bewegung: Kontralateral gehen (rechter Arm + linkes Bein gleichzeitig) vorwärts oder rückwärts. Fehler: Hüfte schwingt, Rücken runden, Knie berühren Boden." },
    { n: "Scapula Push-Ups", e: false, d: "Setup: Hohe Liegestütz-Position, Arme bleiben gestreckt. Bewegung: Brustbein nach unten Richtung Boden absenken (Schulterblätter zusammen), wieder hochdrücken (Schulterblätter spreizen). Sehr klein. Fehler: Ellbogen beugen (das ist ein Liegestütz), zu viel Bewegung. Auch sehr gut zur Schulterprävention." },
    { n: "L-Sit Hold", e: false, d: "Setup: Auf Boden oder Parallettes, Hände neben der Hüfte, Beine gestreckt vor dem Körper. Bewegung: Körper hochstemmen, Beine parallel zum Boden halten. Fortgeschritten. Fehler: Hüfte zu tief, Schultern hochgezogen." },
  ],

  "Kettlebell": [
    { n: "Kettlebell Swing", e: false, d: "Setup: Hüftbreiter Stand, KB einen Schritt vor den Füßen, Hip-Hinge: Hüfte zurück, Rücken gerade, Arme lang. Bewegung: KB nach hinten zwischen den Beinen schwingen, dann Hüfte explosiv strecken (Pop!) — KB schwingt durch Hüftkraft auf Brust- bis Schulterhöhe. Arme bleiben passiv. Fehler: Mit den Armen heben statt aus der Hüfte, in die Knie gehen wie Squat, Rückenrundung." },
    { n: "Goblet Squat", e: false, d: "Setup: KB am Griff vor der Brust mit beiden Händen, Ellbogen zeigen nach unten, Füße schulterbreit. Bewegung: Tiefe Kniebeuge, Ellbogen zwischen Knien, Brust raus, aufrecht aufrichten. Fehler: Vornüberkippen, Knie kippen nach innen, Fersen heben." },
    { n: "KB Front Squat", e: true, d: "Setup: KB im Front Rack einseitig (KB liegt am Unterarm vor der Schulter, Ellbogen hoch), Füße schulterbreit. Bewegung: Aufrechte Kniebeuge mit Anti-Rotation gegen das einseitige Gewicht. Fehler: Oberkörper kippt zur belasteten Seite, Ellbogen sinkt ab." },
    { n: "KB Sumo Deadlift", e: false, d: "Setup: Breiter Stand, Füße leicht außen rotiert, KB zwischen den Füßen, Hip-Hinge bis zum Griff, Rücken gerade, Brust raus. Bewegung: Über die Beine aufrichten, Hüfte schiebt nach vorn, oben Gesäß fest. Kontrolliert ablassen. Fehler: Rückenrundung, ruckartig anheben, mit dem Rücken statt mit den Beinen." },
    { n: "KB Single Arm Row", e: true, d: "Setup: Vorgebeugt im Hip-Hinge, eine Hand auf Bank/Knie als Stütze, andere Hand hält KB hängend. Bewegung: KB Richtung Hüfte ziehen, Ellbogen eng am Körper, Schulterblatt zusammen, kurz halten, langsam zurück. Fehler: Mit dem Oberkörper rotieren, Ellbogen nach außen, Schwung." },
    { n: "Renegade Row", e: true, d: "Setup: Hohe Liegestütz-Position, beide Hände auf Kettlebells. Bewegung: Im Wechsel eine KB zur Hüfte ziehen, Hüfte stabil halten (kein Rotieren!). Sehr core-intensiv. Fehler: Hüfte rotiert, ein Arm sackt ab, Hüfte hängt." },
    { n: "KB Strict Press", e: true, d: "Setup: KB im Front Rack einseitig (am Unterarm vor der Schulter), Füße fest, Core fest. Bewegung: KB senkrecht über Kopf drücken bis Arm voll gestreckt, kontrolliert zurück ins Rack. Fehler: Hohlkreuz, KB nach vorn statt direkt nach oben, mit den Beinen drücken." },
    { n: "KB Push Press", e: true, d: "Setup: Wie KB Strict Press. Bewegung: Leichte Kniebeuge (Dip), explosive Streckung der Beine als Schwungimpuls für die Schulter, Arm streckt nach oben durch. Erlaubt mehr Gewicht als Strict Press. Fehler: Zu tiefer Dip (= Squat), Drücken zu früh ohne Beinimpuls." },
    { n: "KB Snatch", e: true, d: "Setup: KB einarmig am Boden, hüftbreit. Bewegung: Hip-Hinge wie Swing, KB explosiv durch die Hüfte hochbeschleunigen, in einer fließenden Bewegung über Kopf in volle Streckung kommen — Handgelenk dreht im letzten Moment, KB landet sanft hinter der Hand. Fortgeschritten! Fehler: KB knallt aufs Handgelenk, Ellbogen verriegelt nicht, hochziehen wie ein Hochzug." },
    { n: "KB Clean", e: true, d: "Setup: KB am Boden vor sich. Bewegung: Hip-Hinge, KB hochziehen und gleichzeitig den Ellbogen unterdrehen, sodass die KB sanft im Front Rack landet (Daumen Richtung Schulter). Fehler: KB knallt auf den Unterarm, Ellbogen bleibt zu lange weit." },
    { n: "KB Turkish Get-Up", e: true, d: "Setup: Rückenlage, KB einarmig nach oben gestreckt, Arm senkrecht (Auge schaut zur KB), gleiches Bein wie Arm angewinkelt. Bewegung: 7 Schritte: Aufstützen → Hüfte hoch → Standbein nach hinten zum Lunge → aufrichten → wieder zurück. Arm bleibt die ganze Zeit oben/senkrecht. Fehler: Arm kippt, Augen verlieren KB, hetzen." },
    { n: "KB Windmill", e: true, d: "Setup: KB einarmig über Kopf gestreckt, Füße ca. 1,5 schulterbreit, Füße zeigen nach links wenn KB rechts oben. Bewegung: Hüfte zur belasteten Seite schieben, Oberkörper langsam nach vorn/zur Seite absenken bis freie Hand zum Boden, Augen auf KB. Aufrichten. Fehler: KB kippt, Knie der belasteten Seite knickt." },
    { n: "KB Halo", e: false, d: "Setup: KB am Griff vor der Brust mit beiden Händen, Ellbogen hoch. Bewegung: KB langsam um den Kopf kreisen lassen — vor dem Gesicht → über eine Schulter → hinter den Kopf → über die andere Schulter → wieder vor der Brust. Beide Richtungen. Fehler: KB zu tief halten (trifft Hinterkopf), Schultern hochziehen." },
    { n: "KB Farmers Walk", e: true, d: "Setup: KB einseitig oder beidseitig in der Hand neben der Hüfte. Bewegung: Aufrecht gehen, Schultern aktiv unten, Bauch fest, gleichmäßige Schritte. Strecke oder Zeit. Fehler: Zur Seite kippen (besonders einseitig), Schultern hochziehen, schlurfen." },
    { n: "KB Suitcase Carry", e: true, d: "Setup: Wie Farmers Walk, aber bewusst nur einseitig. Bewegung: Gehen ohne zur belasteten Seite zu kippen — der Anti-Rotation-Effekt ist das Trainingsziel. Fehler: Hüfte/Schulter kippen, Oberkörper wandert über das Gewicht." },
    { n: "KB Front Rack Carry", e: true, d: "Setup: KB im Front Rack einseitig oder beidseitig. Bewegung: Aufrechtes Gehen, Ellbogen hoch, Bauch fest. Atmungsherausforderung! Fehler: Ellbogen sinkt, Hohlkreuz." },
    { n: "Sandbag Lunges", e: true, d: "Setup: Sandbag auf Schultern oder vor der Brust (Bear Hug), aufrechter Stand. Bewegung: Ausfallschritte vorwärts oder rückwärts, hinteres Knie absenken, vorderes Knie über Sprunggelenk. Fehler: Vornüberkippen (deshalb gerne Bear Hug-Variante), Schritte zu kurz." },
    { n: "Russian Twist", e: true, d: "Setup: Sitzend, Knie gebeugt, Füße flach (oder schwerer: Füße in der Luft), Oberkörper nach hinten geneigt mit geradem Rücken, KB oder Gewicht in beiden Händen. Bewegung: Oberkörper kontrolliert nach links und rechts rotieren, Bauch fest. Fehler: Rückenrundung, Schwung mit den Armen, zu schnelles Tempo." },
  ],

  "Cardio": [
    { n: "Bike", e: false, d: "Setup: Sattel auf Hüfthöhe, Knie am tiefsten Punkt leicht gebeugt (ca. 25–30°), Lenker gut greifbar, aufrecht oder leicht vorgebeugt. Trittfrequenz 80–100/min für Base-Training. Hinweis: Stufe und Trittfrequenz beide tracken — HF ohne Kontext sagt wenig." },
    { n: "Crosstrainer", e: false, d: "Setup: Aufrecht, ganze Fußsohle auf Pedal, Arme aktiv mitbewegen. Schultern locker, Blick nach vorn. Hinweis: Vorwärts und rückwärts wechseln macht Sinn (andere Muskelgruppen). HF und Stufe tracken." },
    { n: "Laufband", e: false, d: "Setup: Mittig laufen, aufrechte Haltung, Mittelfußaufsatz, Blick weit voraus. 1% Steigung kompensiert den fehlenden Luftwiderstand. Hinweis: Geschwindigkeit + HF + Steigung tracken. Kadenz 170–180 Schritte/min anstreben (verringert Fersensporn-Belastung)." },
    { n: "Laufen", e: false, d: "Allgemeine Lauf-Einheit (Outdoor oder Laufband). Aufrechte Haltung, Mittelfußaufsatz, Blick weit voraus. Atmung gleichmäßig, Kadenz 170–180/min. Bei Outdoor: Distanz, Dauer, HF, Höhenmeter tracken. Bei Laufband: Geschwindigkeit, Steigung, HF tracken." },
    { n: "Schwimmen", e: false, d: "Allgemeine Schwimm-Einheit (Stil egal). Distanz, Zeit und HF tracken. Pace wird automatisch in min/100m berechnet. Für stilspezifische Hinweise siehe Schwimmen Kraul oder Schwimmen Brust." },
    { n: "Schwimmen Kraul", e: false, d: "Technik: Langer Armzug mit Hüftrotation, Atmung zur Seite (nicht heben!), Beinschlag aus der Hüfte. Ausatmen kontinuierlich unter Wasser! Fehler: Kopf zu hoch, Beine sinken, Arme nicht voll durchziehen." },
    { n: "Schwimmen Brust", e: false, d: "Technik: Zugphase + Gleitphase. Gleiten mit gestreckten Armen ist die Erholung — nicht hetzen! Atmung am Ende des Zuges. Fehler: Kein Gleiten, hektischer Beinschlag, Kopf bleibt oben (Nackenschmerz)." },
    { n: "Assault Bike", e: false, d: "Setup: Pedale + Lenker werden gleichzeitig benutzt. Bewegung: Arme und Beine im Wechsel kraftvoll. Für Intervalle: 20–30 sek Vollgas, Pause sitzen lassen. Fehler: Nur Beine oder nur Arme arbeiten." },
    { n: "SkiErg", e: false, d: "Setup: Aufrechter Stand, Griffe oben fassen. Bewegung: Hüfte beugen + Arme kraftvoll nach unten ziehen, dann aufrichten. Aus den Beinen + Lat. Fehler: Nur mit den Armen arbeiten, Rückenrundung." },
    { n: "Seilspringen", e: false, d: "Setup: Aufrecht, Ellbogen am Körper, Handgelenke drehen das Seil (nicht die Schultern). Leicht auf Fußballen. Bewegung: Niedrige Sprünge, knapp über das Seil. Fehler: Zu hoch springen, mit Schultern/Armen statt Handgelenken." },
    { n: "Sled Push", e: false, d: "Setup: Hände an Griffen, Körper ca. 45° vorgeneigt, Beine im Lunge-Setup. Bewegung: Kleine schnelle Schritte, Hüfte und Beine drücken den Schlitten. Fehler: Aufrecht stehen (kein Druck möglich), zu lange Schritte." },
    { n: "Sled Pull", e: false, d: "Setup: Seil vom Schlitten greifen, leicht vorgebeugt, stabiler Stand. Bewegung: Hand über Hand das Seil zu sich ziehen, Beine fest, Core stabil. Fehler: Mit dem Rücken ziehen statt mit Lat." },
    { n: "Rudergerät", e: false, d: "Setup: Füße fest, Schienbein senkrecht in Catch-Position, Arme gestreckt, Schultern locker. Bewegung: Beine drücken → Hüfte öffnet → Arme ziehen zur Brust. Recovery in umgekehrter Reihenfolge. Fehler: Erst Arme ziehen (statt Beine zuerst), Rückenrundung." },
  ],

  "Prävention Ferse": [
    { n: "Plantarfaszien-Massage", e: true, d: "Setup: Ball oder Mini-Faszienrolle unter Fußsohle, Sitzposition. Bewegung: Mit moderatem Druck unter dem Fuß rollen, an empfindlichen Stellen kurz verweilen (15–20 sek). 60–90 sek pro Seite. Fehler: Zu viel Druck (Reizung), Rollen mit gestreckten Zehen." },
    { n: "Plantarfaszien-Dehnung", e: true, d: "Setup: Sitzend, betroffenen Fuß über das andere Knie. Bewegung: Zehen aktiv mit der Hand zum Schienbein ziehen, leichte Spannung in der Fußsohle, 30–45 sek halten. 2–3x pro Seite. Fehler: Zu starker Zug (Schmerz), Fuß zur Seite drehen." },
    { n: "Exzentrisches Wadenheben", e: true, d: "Setup: Auf einer Stufe, Fußballen vorn, Fersen hängen frei. Bewegung: Auf Zehenspitzen hoch (mit beiden Beinen oder dem gesunden), dann auf das betroffene Bein wechseln und sehr langsam (3 Sek!) die Ferse unter Stufenkante absenken. Mit dem gesunden Bein wieder hoch. 3x12. Fehler: Zu schnelles Absenken, beidseitig statt einbeinig (Effekt geringer)." },
    { n: "Wadendehnung (gestreckt)", e: true, d: "Setup: Vor einer Wand, betroffenes Bein gestreckt nach hinten, Ferse fest am Boden, vorderes Bein gebeugt, Hände an die Wand. Bewegung: Hüfte zur Wand schieben, Wadenstreckung halten (45–60 sek). Zielt auf den Gastrocnemius. Fehler: Hintere Ferse hebt, Hohlkreuz." },
    { n: "Wadendehnung (gebeugt)", e: true, d: "Setup: Wie Wadendehnung gestreckt, aber das hintere Bein leicht gebeugt. Bewegung: Hüfte sinkt nach unten, Dehnung zieht tiefer in die Wade (Soleus). 45–60 sek. Fehler: Knie zu tief, Ferse hebt." },
    { n: "Zehen-Greif-Übung", e: true, d: "Setup: Sitzend, Handtuch auf dem Boden, Ferse fest. Bewegung: Mit den Zehen das Handtuch zu sich heranziehen, dann wieder von sich wegschieben. 2–3 min pro Seite. Trainiert die Fußmuskulatur." },
    { n: "Single-Leg Balance", e: true, d: "Setup: Auf einem Bein stehen, freies Bein leicht angehoben. Bewegung: 30–60 sek halten, Augen offen, dann eventuell mit geschlossenen Augen. Trainiert Fußstabilisatoren. Fehler: Hand abstützen ohne Notwendigkeit." },
  ],

  "Prävention Schulter": [
    { n: "Schulterdislocation", e: false, d: "Setup: Theraband oder Stab im weiten Obergriff vor dem Körper. Bewegung: Mit gestreckten Armen langsam über den Kopf nach hinten führen, dann zurück. Griff so weit, dass es ohne Schmerz geht — mit der Zeit enger. 12–15 Wdh. Fehler: Zu enger Griff zu früh (Schmerz), Arme beugen." },
    { n: "Außenrotation Kabelzug", e: true, d: "Siehe Kabelzug. 2x10–12 mit sehr leichtem Gewicht (1,25–2,5 kg). Tägliches Pflichtprogramm bei Schulterbelastung." },
    { n: "Innenrotation Kabelzug", e: true, d: "Siehe Kabelzug. 2x10 mit sehr leichtem Gewicht. Komplementär zur Außenrotation." },
    { n: "BWS-Rotation", e: true, d: "Setup: Seitlage, Knie 90° angezogen, beide Arme vor der Brust gestreckt (Open-Book-Stretch). Bewegung: Den oberen Arm langsam zur Gegenseite öffnen (Buch aufschlagen), Blick folgt der Hand, kurz halten, zurück. 10/Seite. Fehler: Knie heben mit (sollten am Boden bleiben), zu schnelle Bewegung." },
    { n: "Sleeper Stretch", e: true, d: "Setup: Seitlage auf der zu dehnenden Schulter, Oberarm 90° zum Körper, Unterarm zeigt nach oben. Bewegung: Mit der oberen Hand den Unterarm sanft zum Boden drücken (Innenrotation), 30–45 sek halten. Fehler: Schmerzhafter Druck, Schulterblatt rollt nach vorn (vorher fixieren!)." },
    { n: "Y-T-W Raises", e: false, d: "Setup: Bauchlage auf Bank/Boden, Arme hängen entspannt. Bewegung: Arme in Y-Form (nach vorn-oben) heben, 1 sek halten. Dann T (zur Seite). Dann W (Ellbogen 90°, Arme rückwärts). Je 8–10 Wdh, kein oder sehr leichtes Gewicht. Fehler: Schultern hochziehen, mit Schwung, Hohlkreuz." },
    { n: "Pec-Minor-Dehnung", e: true, d: "Setup: Arm an Türrahmen oder Wand 90°, Hand höher als Schulter, einen Schritt vor und Körper wegdrehen. Bewegung: Brust öffnet sich, leichte Dehnung im vorderen Schulter-/Brustbereich, 30 sek halten. Fehler: Zu starker Druck, Schulter rollt nach oben." },
    { n: "Band Pull-Apart", e: false, d: "Setup: Theraband schulterbreit vor der Brust, Arme gestreckt. Bewegung: Band zur Seite auseinanderziehen, Schulterblätter zusammen, kurz halten, kontrolliert zurück. 15–20 Wdh. Fehler: Schultern hochziehen, Schwung." },
    { n: "Wall Slides", e: false, d: "Setup: Mit Rücken, Gesäß und Hinterkopf an der Wand, Arme im W. Bewegung: Arme an der Wand entlang nach oben schieben (in Y-Position), dann wieder zurück. Wand-Kontakt halten! Fehler: Arme verlieren Wandkontakt, Hohlkreuz." },
  ],
};

// Get exercise info by name
export function getExerciseInfo(name) {
  for (const cat of Object.values(EXERCISE_LIB)) {
    const found = cat.find(x => x.n === name);
    if (found) return found;
  }
  return null;
}

// All canonical exercise names from the library, deduplicated and sorted
export function getAllExerciseNames() {
  const names = new Set();
  for (const cat of Object.values(EXERCISE_LIB)) {
    for (const ex of cat) names.add(ex.n);
  }
  return [...names].sort((a, b) => a.localeCompare(b, 'de', { sensitivity: 'base' }));
}
