export const SEED_DATA = [
  {
    "datum": "2026-01-28",
    "uebung": "Crosstrainer",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "15 min",
    "gewicht": "–",
    "bem": "locker–moderat"
  },
  {
    "datum": "2026-01-28",
    "uebung": "Beinpresse",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "10",
    "gewicht": "12,5 kg",
    "bem": "kontrolliert"
  },
  {
    "datum": "2026-01-28",
    "uebung": "Beinbeuger",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "10",
    "gewicht": "20 kg",
    "bem": "einbeinig"
  },
  {
    "datum": "2026-01-28",
    "uebung": "Bulgarian Split Squat",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": true,
    "saetze": 3,
    "wdh": "8",
    "gewicht": "–",
    "bem": "stabil"
  },
  {
    "datum": "2026-01-28",
    "uebung": "Rückenstrecker",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "10",
    "gewicht": "+5 kg",
    "bem": "Scheibe auf Brust"
  },
  {
    "datum": "2026-01-28",
    "uebung": "Plank",
    "geraet": "Core",
    "typ": "eigengewicht",
    "einseitig": false,
    "saetze": 3,
    "wdh": "60 Sek",
    "gewicht": "–",
    "bem": "statisch"
  },
  {
    "datum": "2026-01-28",
    "uebung": "Latzug",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "35 kg",
    "bem": "sauber"
  },
  {
    "datum": "2026-01-28",
    "uebung": "Brustpresse",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "22,5 kg",
    "bem": "kontrolliert"
  },
  {
    "datum": "2026-01-28",
    "uebung": "Schulterpresse",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "10",
    "gewicht": "12,5 kg",
    "bem": "sitzend"
  },
  {
    "datum": "2026-01-28",
    "uebung": "Face Pulls",
    "geraet": "Kabel",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "8",
    "gewicht": "5 kg",
    "bem": "Schulterstabi"
  },
  {
    "datum": "2026-01-28",
    "uebung": "Bike",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "15 min",
    "gewicht": "",
    "bem": "konstant",
    "stufe": "Stufe 15"
  },
  {
    "datum": "2026-01-28",
    "uebung": "Exzentrisches Wadenheben",
    "geraet": "Prävention",
    "typ": "praevention",
    "einseitig": false,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "–",
    "bem": "Fersensporn"
  },
  {
    "datum": "2026-01-29",
    "uebung": "Crosstrainer",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "10 min",
    "gewicht": "",
    "bem": "Aufwärmen",
    "stufe": "Stufe 8 / 69 U/min"
  },
  {
    "datum": "2026-01-29",
    "uebung": "Bike",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "5 min",
    "gewicht": "",
    "bem": "Einrollen Ø HF 128 bei Bike gesamt",
    "hf": 128,
    "stufe": "Stufe 9"
  },
  {
    "datum": "2026-01-29",
    "uebung": "Bike",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 3,
    "wdh": "5 min",
    "gewicht": "",
    "bem": "Intervalle Ø HF 128 bei Bike gesamt",
    "hf": 128,
    "stufe": "Stufe 13 / 85 U/min"
  },
  {
    "datum": "2026-01-29",
    "uebung": "Bike",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 2,
    "wdh": "2 min",
    "gewicht": "",
    "bem": "Pausen zwischen Intervallen Ø HF 128",
    "hf": 128,
    "stufe": "Stufe 8 / 75 U/min"
  },
  {
    "datum": "2026-01-29",
    "uebung": "Bike",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "5 min",
    "gewicht": "",
    "bem": "Ausrollen Ø HF 128 bei Bike gesamt",
    "hf": 128,
    "stufe": "Stufe 8 / 75 U/min"
  },
  {
    "datum": "2026-01-29",
    "uebung": "Pallof Press",
    "geraet": "Kabelzug",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "7,5 kg",
    "bem": "Core Anti-Rotation"
  },
  {
    "datum": "2026-01-29",
    "uebung": "Seitstütz",
    "geraet": "Core",
    "typ": "eigengewicht",
    "einseitig": true,
    "saetze": 3,
    "wdh": "35 Sek",
    "gewicht": "–",
    "bem": "Laterale Rumpfstabilität"
  },
  {
    "datum": "2026-01-29",
    "uebung": "Rückenstrecker",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 2,
    "wdh": "12",
    "gewicht": "2,5 kg",
    "bem": "locker/regenerativ"
  },
  {
    "datum": "2026-01-29",
    "uebung": "Glute Bridge",
    "geraet": "Boden",
    "typ": "eigengewicht",
    "einseitig": false,
    "saetze": 3,
    "wdh": "15",
    "gewicht": "–",
    "bem": "Eigengewicht"
  },
  {
    "datum": "2026-01-29",
    "uebung": "Rudermaschine (brustgestützt)",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "30 kg",
    "bem": "Oberkörper Zug"
  },
  {
    "datum": "2026-01-29",
    "uebung": "Latzug",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 2,
    "wdh": "15",
    "gewicht": "25 kg",
    "bem": "locker"
  },
  {
    "datum": "2026-01-29",
    "uebung": "Schulter-Außenrotation",
    "geraet": "Kabelzug",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 2,
    "wdh": "10",
    "gewicht": "2,5 kg",
    "bem": "erste Durchführung"
  },
  {
    "datum": "2026-01-29",
    "uebung": "Exzentrisches Wadenheben",
    "geraet": "Prävention",
    "typ": "praevention",
    "einseitig": true,
    "saetze": 2,
    "wdh": "10",
    "gewicht": "–",
    "bem": "Schmerz 1–2/10"
  },
  {
    "datum": "2026-01-29",
    "uebung": "Plantarfaszien-Massage",
    "geraet": "Prävention",
    "typ": "praevention",
    "einseitig": true,
    "saetze": 3,
    "wdh": "45 Sek",
    "gewicht": "–",
    "bem": "Ausrollen Fußsohle"
  },
  {
    "datum": "2026-01-30",
    "uebung": "Crosstrainer",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "10 min",
    "gewicht": "65 U/min",
    "bem": "Ø HF 145",
    "hf": 145
  },
  {
    "datum": "2026-01-30",
    "uebung": "Bike",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "5 min",
    "gewicht": "",
    "bem": "Einrollen Ø HF 138 bei Bike gesamt",
    "hf": 138,
    "stufe": "Stufe 9 / 75 U/min"
  },
  {
    "datum": "2026-01-30",
    "uebung": "Bike",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "15 min",
    "gewicht": "",
    "bem": "Konstant Ø HF 138 bei Bike gesamt",
    "hf": 138,
    "stufe": "Stufe 12 / 90 U/min"
  },
  {
    "datum": "2026-01-30",
    "uebung": "Bike",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "5 min",
    "gewicht": "",
    "bem": "Ausrollen Ø HF 138 bei Bike gesamt",
    "hf": 138,
    "stufe": "Stufe 8 / 75 U/min"
  },
  {
    "datum": "2026-01-30",
    "uebung": "Wechsel Bike zu Lauf",
    "geraet": "–",
    "typ": "sonstige",
    "einseitig": false,
    "saetze": 1,
    "wdh": "2 min",
    "gewicht": "–",
    "bem": "Übergang"
  },
  {
    "datum": "2026-01-30",
    "uebung": "Laufband",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "8 min",
    "gewicht": "9 km/h / 1 %",
    "bem": "Ø HF 145 keine Schmerzen Ferse",
    "hf": 145
  },
  {
    "datum": "2026-01-30",
    "uebung": "Pallof Press",
    "geraet": "Kabelzug",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "5 kg",
    "bem": "Core Anti-Rotation"
  },
  {
    "datum": "2026-01-30",
    "uebung": "Seitstütz",
    "geraet": "Core",
    "typ": "eigengewicht",
    "einseitig": true,
    "saetze": 2,
    "wdh": "35 Sek",
    "gewicht": "–",
    "bem": "Laterale Rumpfstabilität"
  },
  {
    "datum": "2026-01-30",
    "uebung": "Glute Bridge",
    "geraet": "Boden",
    "typ": "eigengewicht",
    "einseitig": false,
    "saetze": 2,
    "wdh": "15",
    "gewicht": "–",
    "bem": "Eigengewicht"
  },
  {
    "datum": "2026-01-30",
    "uebung": "Exzentrisches Wadenheben",
    "geraet": "Prävention",
    "typ": "praevention",
    "einseitig": true,
    "saetze": 3,
    "wdh": "10",
    "gewicht": "–",
    "bem": "keine Schmerzen"
  },
  {
    "datum": "2026-01-30",
    "uebung": "Plantarfaszien-Massage",
    "geraet": "Prävention",
    "typ": "praevention",
    "einseitig": true,
    "saetze": 3,
    "wdh": "45 Sek",
    "gewicht": "–",
    "bem": "Abschluss"
  },
  {
    "datum": "2026-02-02",
    "uebung": "Laufen",
    "geraet": "Laufband",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "21 min",
    "gewicht": "10 km/h; 1 % Steigung",
    "bem": "Hotel; Fersensporn 1–2/10"
  },
  {
    "datum": "2026-02-02",
    "uebung": "Liegestütze",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": false,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "–",
    "bem": "Hotel"
  },
  {
    "datum": "2026-02-02",
    "uebung": "Plank",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": false,
    "saetze": 3,
    "wdh": "45 sek",
    "gewicht": "–",
    "bem": "Hotel"
  },
  {
    "datum": "2026-02-02",
    "uebung": "Seitstütz",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": true,
    "saetze": 2,
    "wdh": "30 sek",
    "gewicht": "–",
    "bem": "Hotel"
  },
  {
    "datum": "2026-02-02",
    "uebung": "Dead Bug",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": true,
    "saetze": 2,
    "wdh": "10",
    "gewicht": "–",
    "bem": "Hotel"
  },
  {
    "datum": "2026-02-02",
    "uebung": "Plantarfaszien-Dehnung",
    "geraet": "Dehnung",
    "typ": "praevention",
    "einseitig": true,
    "saetze": 2,
    "wdh": "45 sek",
    "gewicht": "–",
    "bem": "Hotel"
  },
  {
    "datum": "2026-02-08",
    "uebung": "Plank",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": false,
    "saetze": 2,
    "wdh": "60 sek",
    "gewicht": "–",
    "bem": "–"
  },
  {
    "datum": "2026-02-08",
    "uebung": "Seitstütz",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": true,
    "saetze": 2,
    "wdh": "40 sek",
    "gewicht": "–",
    "bem": "–"
  },
  {
    "datum": "2026-02-08",
    "uebung": "Bike",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "22 min",
    "gewicht": "",
    "bem": "Ø HF 144",
    "hf": 144,
    "stufe": "Stufe 12"
  },
  {
    "datum": "2026-02-08",
    "uebung": "Russian Twist",
    "geraet": "Gewichtsball",
    "typ": "eigengewicht",
    "einseitig": true,
    "saetze": 3,
    "wdh": "15",
    "gewicht": "5 kg",
    "bem": "–"
  },
  {
    "datum": "2026-02-08",
    "uebung": "Liegestütze",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": false,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "–",
    "bem": "–"
  },
  {
    "datum": "2026-02-08",
    "uebung": "Superman",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": false,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "–",
    "bem": "–"
  },
  {
    "datum": "2026-02-08",
    "uebung": "Bizepscurls",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "25 kg",
    "bem": "–"
  },
  {
    "datum": "2026-02-08",
    "uebung": "Exzentrisches Wadenheben",
    "geraet": "Prävention",
    "typ": "praevention",
    "einseitig": true,
    "saetze": 2,
    "wdh": "12",
    "gewicht": "–",
    "bem": "Fersensporn"
  },
  {
    "datum": "2026-02-08",
    "uebung": "Plantarfaszien-Dehnung",
    "geraet": "Prävention",
    "typ": "praevention",
    "einseitig": true,
    "saetze": 2,
    "wdh": "45 sek",
    "gewicht": "–",
    "bem": "Fersensporn"
  },
  {
    "datum": "2026-02-09",
    "uebung": "Laufen",
    "geraet": "Outdoor",
    "typ": "outdoor",
    "einseitig": false,
    "saetze": 1,
    "wdh": "6,03 km",
    "gewicht": "",
    "bem": "Ø HF 159; Schmerz links 1/10 während Lauf; 4/10 morgens im Bett",
    "hf": 159,
    "pace": "Pace 5:55 min/km"
  },
  {
    "datum": "2026-02-15",
    "uebung": "Bike",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "14 min",
    "gewicht": "",
    "bem": "Ø HF 114",
    "hf": 114,
    "stufe": "Stufe 10 / 90 U/min"
  },
  {
    "datum": "2026-02-15",
    "uebung": "Adduktoren",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "15",
    "gewicht": "50 kg",
    "bem": "Schmerz Leiste danach 3/10"
  },
  {
    "datum": "2026-02-15",
    "uebung": "Abduktoren",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "15",
    "gewicht": "50 kg",
    "bem": "–"
  },
  {
    "datum": "2026-02-15",
    "uebung": "Beinpresse",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "15 kg",
    "bem": "–"
  },
  {
    "datum": "2026-02-15",
    "uebung": "Beinstrecker",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "20 kg",
    "bem": "–"
  },
  {
    "datum": "2026-02-15",
    "uebung": "Beinbeuger",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "15 kg",
    "bem": "–"
  },
  {
    "datum": "2026-02-15",
    "uebung": "Plank",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": false,
    "saetze": 3,
    "wdh": "60 sek",
    "gewicht": "–",
    "bem": "–"
  },
  {
    "datum": "2026-02-15",
    "uebung": "Seitstütz",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": true,
    "saetze": 3,
    "wdh": "40 sek",
    "gewicht": "–",
    "bem": "–"
  },
  {
    "datum": "2026-02-15",
    "uebung": "Pallof Press",
    "geraet": "Kabelzug",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "6,25 kg",
    "bem": "–"
  },
  {
    "datum": "2026-02-15",
    "uebung": "Rückenstrecker",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "5 kg",
    "bem": "Scheibe auf Brust"
  },
  {
    "datum": "2026-02-15",
    "uebung": "Bike",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "30 min",
    "gewicht": "",
    "bem": "Ø HF 139",
    "hf": 139,
    "stufe": "Stufe 13 / 91 U/min"
  },
  {
    "datum": "2026-02-15",
    "uebung": "Exzentrisches Wadenheben",
    "geraet": "Prävention",
    "typ": "praevention",
    "einseitig": true,
    "saetze": 2,
    "wdh": "10",
    "gewicht": "–",
    "bem": "Fersensporn"
  },
  {
    "datum": "2026-02-15",
    "uebung": "Plantarfaszien-Dehnung",
    "geraet": "Prävention",
    "typ": "praevention",
    "einseitig": true,
    "saetze": 2,
    "wdh": "45 sek",
    "gewicht": "–",
    "bem": "Fersensporn"
  },
  {
    "datum": "2026-02-17",
    "uebung": "Bike (Aufwärmen)",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "10 min",
    "gewicht": "",
    "bem": "Ø HF 148; 94 U/min",
    "hf": 148,
    "stufe": "Stufe 10"
  },
  {
    "datum": "2026-02-17",
    "uebung": "Schulterpresse",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "10",
    "gewicht": "12,5 kg",
    "bem": "–"
  },
  {
    "datum": "2026-02-17",
    "uebung": "Brustpresse",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "22,5 kg",
    "bem": "–"
  },
  {
    "datum": "2026-02-17",
    "uebung": "Bizepscurls",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "",
    "bem": "≈ 25 kg auf anderer Maschine",
    "stufe": "Stufe 9"
  },
  {
    "datum": "2026-02-17",
    "uebung": "Latzug",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "32,5 kg",
    "bem": "Ziel war 35 kg; falsch abgelesen"
  },
  {
    "datum": "2026-02-17",
    "uebung": "Trizeps-Pushdown",
    "geraet": "Kabelzug",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "10",
    "gewicht": "12,5 kg",
    "bem": "Erstmalig; 10 statt 12 Wdh"
  },
  {
    "datum": "2026-02-17",
    "uebung": "Pallof Press",
    "geraet": "Kabelzug",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "7,5 kg",
    "bem": "Steigerung von 6,25 kg"
  },
  {
    "datum": "2026-02-17",
    "uebung": "Face Pulls",
    "geraet": "Kabelzug",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "10",
    "gewicht": "7,5 kg",
    "bem": "Steigerung von 5 kg; bei 12,5 kg kippt Körper"
  },
  {
    "datum": "2026-02-17",
    "uebung": "Rudermaschine (brustgestützt)",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "32,5 kg",
    "bem": "Steigerung von 30 kg"
  },
  {
    "datum": "2026-02-17",
    "uebung": "Bike (Abschluss)",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "25 min",
    "gewicht": "",
    "bem": "Ø HF 159; 92 U/min",
    "hf": 159,
    "stufe": "Stufe 12"
  },
  {
    "datum": "2026-02-19",
    "uebung": "Plank",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": false,
    "saetze": 3,
    "wdh": "60 sek",
    "gewicht": "–",
    "bem": "–"
  },
  {
    "datum": "2026-02-19",
    "uebung": "Seitstütz",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": true,
    "saetze": 3,
    "wdh": "45 sek",
    "gewicht": "–",
    "bem": "–"
  },
  {
    "datum": "2026-02-20",
    "uebung": "Bike (Aufwärmen)",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "10 min",
    "gewicht": "",
    "bem": "Ø HF 115; 85 U/min",
    "hf": 115,
    "stufe": "Stufe 10"
  },
  {
    "datum": "2026-02-20",
    "uebung": "Beinpresse",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "17,5 kg",
    "bem": "Steigerung von 15 kg"
  },
  {
    "datum": "2026-02-20",
    "uebung": "Beinbeuger",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "15 kg",
    "bem": "17,5 kg zu schwer; 15 kg fordernd"
  },
  {
    "datum": "2026-02-20",
    "uebung": "Beinstrecker",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "20 kg",
    "bem": "22,5 kg zu schwer; mit Unterbrechung geschafft"
  },
  {
    "datum": "2026-02-20",
    "uebung": "Adduktoren",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "45 kg",
    "bem": "Reduziert von 50 kg; keine Leistenschmerzen"
  },
  {
    "datum": "2026-02-20",
    "uebung": "Abduktoren",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "50 kg",
    "bem": "12 statt 15 Wdh (falsch abgelesen)"
  },
  {
    "datum": "2026-02-20",
    "uebung": "Rückenstrecker",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "+5 kg",
    "bem": "Scheibe auf Brust"
  },
  {
    "datum": "2026-02-20",
    "uebung": "Russian Twist",
    "geraet": "Kettlebell",
    "typ": "eigengewicht",
    "einseitig": true,
    "saetze": 3,
    "wdh": "15",
    "gewicht": "6 kg",
    "bem": "Steigerung von 5 kg"
  },
  {
    "datum": "2026-02-20",
    "uebung": "Glute Bridge",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": false,
    "saetze": 3,
    "wdh": "15",
    "gewicht": "–",
    "bem": "–"
  },
  {
    "datum": "2026-02-20",
    "uebung": "Bike (Abschluss)",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "26 min",
    "gewicht": "",
    "bem": "Ø HF 138; 91 U/min",
    "hf": 138,
    "stufe": "Stufe 12"
  },
  {
    "datum": "2026-02-20",
    "uebung": "Plantarfaszien-Dehnung",
    "geraet": "Prävention",
    "typ": "praevention",
    "einseitig": true,
    "saetze": 3,
    "wdh": "45 sek",
    "gewicht": "–",
    "bem": "zuhause"
  },
  {
    "datum": "2026-02-20",
    "uebung": "Exzentrisches Wadenheben",
    "geraet": "Prävention",
    "typ": "praevention",
    "einseitig": true,
    "saetze": 2,
    "wdh": "10",
    "gewicht": "–",
    "bem": "zuhause"
  },
  {
    "datum": "2026-02-20",
    "uebung": "Wadendehnung (gestreckt)",
    "geraet": "Prävention",
    "typ": "praevention",
    "einseitig": true,
    "saetze": 2,
    "wdh": "60 sek",
    "gewicht": "–",
    "bem": "zuhause"
  },
  {
    "datum": "2026-02-20",
    "uebung": "Wadendehnung (gebeugt)",
    "geraet": "Prävention",
    "typ": "praevention",
    "einseitig": true,
    "saetze": 2,
    "wdh": "60 sek",
    "gewicht": "–",
    "bem": "zuhause"
  },
  {
    "datum": "2026-02-21",
    "uebung": "Bike (Aufwärmen)",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "10 min",
    "gewicht": "",
    "bem": "Ø HF 121; 86 U/min",
    "hf": 121,
    "stufe": "Stufe 10"
  },
  {
    "datum": "2026-02-21",
    "uebung": "Brustpresse",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "22,5 kg",
    "bem": "Supersatz A"
  },
  {
    "datum": "2026-02-21",
    "uebung": "Rudermaschine (brustgestützt)",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "35 kg",
    "bem": "Supersatz A; Steigerung von 32,5 kg"
  },
  {
    "datum": "2026-02-21",
    "uebung": "Schulterpresse",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "10",
    "gewicht": "15 kg",
    "bem": "Supersatz B; Steigerung von 12,5 kg"
  },
  {
    "datum": "2026-02-21",
    "uebung": "Latzug",
    "geraet": "Maschine",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "35 kg",
    "bem": "Supersatz B"
  },
  {
    "datum": "2026-02-21",
    "uebung": "Bizepscurls",
    "geraet": "Kabelzug",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "12,5 kg",
    "bem": "Supersatz C; am Kabelzug"
  },
  {
    "datum": "2026-02-21",
    "uebung": "Trizeps-Pushdown",
    "geraet": "Kabelzug",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "12,5 kg",
    "bem": "Supersatz C; 12 Wdh geschafft"
  },
  {
    "datum": "2026-02-21",
    "uebung": "Face Pulls",
    "geraet": "Kabelzug",
    "typ": "maschine",
    "einseitig": false,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "7,5 kg",
    "bem": "Supersatz D; 12 Wdh geschafft"
  },
  {
    "datum": "2026-02-21",
    "uebung": "Plank",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": false,
    "saetze": 3,
    "wdh": "60 sek",
    "gewicht": "–",
    "bem": "Supersatz D"
  },
  {
    "datum": "2026-02-21",
    "uebung": "Pallof Press",
    "geraet": "Kabelzug",
    "typ": "maschine",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "7,5 kg",
    "bem": "–"
  },
  {
    "datum": "2026-02-21",
    "uebung": "Bike (Abschluss)",
    "geraet": "Cardio",
    "typ": "cardio_gym",
    "einseitig": false,
    "saetze": 1,
    "wdh": "25 min",
    "gewicht": "",
    "bem": "Ø HF 135; 92 U/min; reduziert wegen Infekt",
    "hf": 135,
    "stufe": "Stufe 11"
  },
  {
    "datum": "2026-02-26",
    "uebung": "Laufen",
    "geraet": "Outdoor",
    "typ": "outdoor",
    "einseitig": false,
    "saetze": 1,
    "wdh": "1:09:14 / 12,04 km",
    "gewicht": "",
    "bem": "Ø HF 168; Wettkampfdistanz erreicht; leichte Spannung Achillessehne, kein Schmerz",
    "hf": 168,
    "pace": "Pace 5:45 min/km"
  },
  {
    "datum": "2026-03-02",
    "uebung": "Schwimmen",
    "geraet": "Schwimmbad",
    "typ": "schwimmen",
    "einseitig": false,
    "saetze": 1,
    "wdh": "4:41 min / 135 m",
    "gewicht": "",
    "bem": "Ø HF 138; mit Unterbrechungen; Kraul/Brust gemischt; erste dokumentierte Schwimmeinheit",
    "hf": 138,
    "pace": "Pace 3:28 min/100m"
  },
  {
    "datum": "2026-04-18",
    "uebung": "Bike",
    "geraet": "Outdoor",
    "typ": "outdoor",
    "einseitig": false,
    "saetze": 1,
    "wdh": "34,75 km / 2:22:52",
    "gewicht": "",
    "bem": "Ø HF 148; 283 Höhenmeter",
    "hf": 148,
    "pace": "Avg. 14,6 km/h",
    "hoehenmeter": 283
  },
  {
    "datum": "2026-04-19",
    "uebung": "Laufen",
    "geraet": "Outdoor",
    "typ": "outdoor",
    "einseitig": false,
    "saetze": 1,
    "wdh": "7,01 km / 41:50 min",
    "gewicht": "",
    "bem": "Ø HF 156",
    "hf": 156,
    "pace": "Pace 5:58 min/km"
  },
  {
    "datum": "2026-04-22",
    "uebung": "Seitstütz",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": true,
    "saetze": 3,
    "wdh": "45 sek",
    "gewicht": "–",
    "bem": ""
  },
  {
    "datum": "2026-04-22",
    "uebung": "Plank",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": false,
    "saetze": 3,
    "wdh": "60 sek",
    "gewicht": "–",
    "bem": ""
  },
  {
    "datum": "2026-04-22",
    "uebung": "Liegestütze",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": false,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "–",
    "bem": ""
  },
  {
    "datum": "2026-04-22",
    "uebung": "Glute Bridge",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": false,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "–",
    "bem": ""
  },
  {
    "datum": "2026-04-22",
    "uebung": "Dead Bug",
    "geraet": "Eigengewicht",
    "typ": "eigengewicht",
    "einseitig": true,
    "saetze": 3,
    "wdh": "12",
    "gewicht": "–",
    "bem": ""
  }
];
